CATEGORIAS = [
	    (1, 'Administração e Negócios'),
	    (2, 'Arquitetura e Urbanismo'),
	    (3, 'Artes'),
	    (4, 'Auto-ajuda'),
	    (5, 'Biografias'),
	    (6, 'Ciências'),
	    (7, 'Concursos'),
	    (8, 'Direito'),
	    (9, 'Ficção'),
	    (10, 'História'),
	    (11, 'Informática'),
	    (12, 'Literatura Estrangeira'),
	    (13, 'Literatura Infantil'),
	    (14, 'Literatura Nacional'),
	    (15, 'Outros'),
	]
