# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-17 02:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('livros', '0003_livro_disponivel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emprestimo', models.DateTimeField(auto_now_add=True, verbose_name='Data de Empréstimo')),
                ('data_devolucao', models.DateTimeField(null=True, verbose_name='Data de Devolução')),
                ('devolvido', models.BooleanField(default=False)),
                ('livros_solicitados', models.ManyToManyField(to='livros.Livro')),
                ('usuario_devolucao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_devolucao', to=settings.AUTH_USER_MODEL)),
                ('usuario_emprestimo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_emprestimo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
