# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-17 03:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('solicitacao', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitacao',
            name='usuario_devolucao',
        ),
        migrations.RemoveField(
            model_name='solicitacao',
            name='usuario_emprestimo',
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='usuario_solicitado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='usuario_solicitante',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='solicitante', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
