# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-17 03:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao', '0002_auto_20170517_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao',
            name='usuario_solicitado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='solicitado', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
