# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-03 15:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('categoria', models.SmallIntegerField(choices=[(1, 'Administração e Negócios'), (2, 'Arquitetura e Urbanismo'), (3, 'Artes'), (4, 'Auto-ajuda'), (5, 'Biografias'), (6, 'Ciências'), (7, 'Concursos'), (8, 'Direito'), (9, 'Ficção'), (10, 'História'), (11, 'Informática'), (12, 'Literatura Estrangeira'), (13, 'Literatura Infantil'), (14, 'Literatura Nacional'), (15, 'Outros')])),
                ('editora', models.CharField(max_length=100, verbose_name='Editora')),
                ('autor', models.CharField(max_length=100, verbose_name='Autor')),
                ('ano', models.IntegerField()),
                ('idioma', models.CharField(max_length=30, verbose_name='Idioma')),
                ('image', models.ImageField(blank=True, upload_to='livros', verbose_name='Imagem')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
