# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-03 23:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livros', to=settings.AUTH_USER_MODEL),
        ),
    ]
