# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-03 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('categoria', models.SmallIntegerField(choices=[(1, 'Estudo'), (2, 'Lazer'), (3, 'Esporte')])),
                ('status', models.BooleanField(choices=[(True, 'Disponível'), (False, 'Indisponível')])),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('image', models.ImageField(blank=True, upload_to='images')),
            ],
        ),
    ]
